# ==== Site basics ====
title: Quantum Information Box
tagline: Notes, research, and posts
description: Quantum Computing, Quantum Information, AI, Information Theory, and Security
lang: en
timezone: America/New York

# ==== URLs ====
# For a project site 
url: "https://bmagginisresearch.github.io"
baseurl: "/Quantum-Information-Box"
theme_mode: auto 
remote_theme: "cotes2020/jekyll-theme-chirpy"

# If you later switch to a user site (repo named USERNAME.github.io),
# remove baseurl and keep only:
# url: "https://bmagginisresearch.github.io"

# ==== Theme ====
remote_theme: "cotes2020/jekyll-theme-chirpy"
theme_mode: auto 

# ==== Author & socials ====
author:
name: "Billy Magginis"
avatar: "/assets/img/avatar.png"
bio: "InfoSec GRC + quantum computing researcher."
location: "USA"


# Sidebar social 
social:
  github: bmagginisresearch 
  linkedin: william-magginis-39440a57
  rss: true

# ==== Build ====
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-remote-theme 

# ==== Pagination (optional) ====
paginate: 10
paginate: "/page:num"

# ==== Permalinks (optional) ====
permalink: /posts/:title/