title: "Quantum Information Box"
tagline: "Notes, research, and posts"
description: >-
  A technical blog on quantum information, information security, and research.
lang: "en"
timezone: "America/New_York"

url: "https://bmagginisresearch.github.io"   # project site base URL
baseurl: "/Quantum-Information-Box"          # repo path, starts with "/"

remote_theme: "cotes2020/jekyll-theme-chirpy"
theme_mode: "auto"

author:
  name: "Billy Magginis"
  bio: "InfoSec GRC + quantum computing researcher."

# Keep plugins to the minimum first; we'll add others later
plugins:
  - jekyll-remote-theme

# Keep default permalinks first (let the theme handle it)
